name: Clang-Tidy Analysis

on:
    push:
        paths:
            - 'source/library/**'
            - '.clang-tidy'
            - '.github/workflows/run_clang_tidy.yml'
    pull_request:
        paths:
            - 'source/library/**'
            - '.clang-tidy'

jobs:
    run-clang-tidy:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: true 
            - run: sudo apt update
            - name: Get general build tools.
              run: sudo apt install --quiet -y clang-tidy cmake g++ ninja-build jq build-essential
            - name: Get build tools for dependencies.
              run: sudo apt install --quiet -y libwayland-dev libxkbcommon-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
            - run: git submodule update --init --recursive
            # vcpkg install zlib libpng rapidjson ? or update the vcpkg usage?
            - run: cmake --preset=ci-static-analysis
            - name: check compile_commands.json
              run: cat build/compile_commands.json
            - name: Run clang-tidy on the source.
              run: |
                while IFS= read -r file; do
                    clang-tidy "$file" -p "./ci_static_analysis"
                done < <(jq -r '.[].file | select(contains("submodules") | not)' "./ci_static_analysis/compile_commands.json")
