name: Clang-Tidy Analysis

on:
    push:
        paths:
            - 'source/**'
            - '.clang-tidy'
            - '.github/workflows/run_clang_tidy.yml'
    pull_request:
        paths:
            - 'source/**'
            - '.clang-tidy'

jobs:
    clang-tidy:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: true 
            - run: sudo apt update
            - name: Get general build tools.
              run: sudo apt install -y clang-tidy cmake g++ ninja-build
            - name: Get build tools for dependencies.
              run: sudo apt install -y libwayland-dev libxkbcommon-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev
            - run: pwd
            - run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B build
            - run: |
                find source \( -name "*.cpp" -o -name "*.h" -o \) \
                | xargs -I{} clang-tidy {} -p build
